#if GOOS_ucos

#if GOARCH_arm

const structs_t struct_mapping[] = {
    {"OSRedzoneHitHook", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSMemCreate", 0, "OS_MEM", (struct_t)OS_MEM},
    {"OSMemGet", 0, "OS_MEM", (struct_t)OS_MEM},
    {"OSMemPut", 0, "OS_MEM", (struct_t)OS_MEM},
    {"OSTimeDlyResume", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTmrCreate", 0, "OS_TMR", (struct_t)OS_TMR},
    {"OSTmrDel", 0, "OS_TMR", (struct_t)OS_TMR},
    {"OSTmrRemainGet", 0, "OS_TMR", (struct_t)OS_TMR},
    {"OSTmrSet", 0, "OS_TMR", (struct_t)OS_TMR},
    {"OSTmrStart", 0, "OS_TMR", (struct_t)OS_TMR},
    {"OSTmrStateGet", 0, "OS_TMR", (struct_t)OS_TMR},
    {"OSTmrStop", 0, "OS_TMR", (struct_t)OS_TMR},
    {"OSSemCreate", 0, "OS_SEM", (struct_t)OS_SEM},
    {"OSSemDel", 0, "OS_SEM", (struct_t)OS_SEM},
    {"OSSemPend", 0, "OS_SEM", (struct_t)OS_SEM},
    {"OSSemPendAbort", 0, "OS_SEM", (struct_t)OS_SEM},
    {"OSSemPost", 0, "OS_SEM", (struct_t)OS_SEM},
    {"OSSemSet", 0, "OS_SEM", (struct_t)OS_SEM},
    {"OSFlagCreate", 0, "OS_FLAG_GRP", (struct_t)OS_FLAG_GRP},
    {"OSFlagDel", 0, "OS_FLAG_GRP", (struct_t)OS_FLAG_GRP},
    {"OSFlagPend", 0, "OS_FLAG_GRP", (struct_t)OS_FLAG_GRP},
    {"OSFlagPendAbort", 0, "OS_FLAG_GRP", (struct_t)OS_FLAG_GRP},
    {"OSFlagPost", 0, "OS_FLAG_GRP", (struct_t)OS_FLAG_GRP},
    {"res$OSFlagPost", 0, "OS_FLAG_GRP", (struct_t)OS_FLAG_GRP},
    {"OSQCreate", 0, "OS_Q", (struct_t)OS_Q},
    {"OSQDel", 0, "OS_Q", (struct_t)OS_Q},
    {"OSQFlush", 0, "OS_Q", (struct_t)OS_Q},
    {"OSQPend", 0, "OS_Q", (struct_t)OS_Q},
    {"OSQPendAbort", 0, "OS_Q", (struct_t)OS_Q},
    {"OSQPost", 0, "OS_Q", (struct_t)OS_Q},
    {"Mem_SegCreate", 1, "MEM_SEG", (struct_t)MEM_SEG},
    {"Mem_SegClr", 0, "MEM_SEG", (struct_t)MEM_SEG},
    {"Mem_SegAlloc", 1, "MEM_SEG", (struct_t)MEM_SEG},
    {"Mem_SegAllocExt", 1, "MEM_SEG", (struct_t)MEM_SEG},
    {"Mem_SegAllocHW", 1, "MEM_SEG", (struct_t)MEM_SEG},
    {"Mem_SegRemSizeGet", 0, "MEM_SEG", (struct_t)MEM_SEG},
    {"Mem_PoolCreate", 0, "MEM_POOL", (struct_t)MEM_POOL},
    {"Mem_PoolClr", 0, "MEM_POOL", (struct_t)MEM_POOL},
    {"Mem_PoolBlkGet", 0, "MEM_POOL", (struct_t)MEM_POOL},
    {"Mem_PoolBlkFree", 0, "MEM_POOL", (struct_t)MEM_POOL},
    {"Mem_PoolBlkGetNbrAvail", 0, "MEM_POOL", (struct_t)MEM_POOL},
    {"Mem_DynPoolCreate", 1, "MEM_DYN_POOL", (struct_t)MEM_DYN_POOL},
    {"Mem_DynPoolCreate", 2, "MEM_SEG", (struct_t)MEM_SEG},
    {"Mem_DynPoolCreateHW", 1, "MEM_DYN_POOL", (struct_t)MEM_DYN_POOL},
    {"Mem_DynPoolCreateHW", 2, "MEM_SEG", (struct_t)MEM_SEG},
    {"Mem_DynPoolBlkGet", 0, "MEM_DYN_POOL", (struct_t)MEM_DYN_POOL},
    {"Mem_DynPoolBlkFree", 0, "MEM_DYN_POOL", (struct_t)MEM_DYN_POOL},
    {"Mem_DynPoolBlkNbrAvailGet", 0, "MEM_DYN_POOL", (struct_t)MEM_DYN_POOL},
    {"OSMutexCreate", 0, "OS_MUTEX", (struct_t)OS_MUTEX},
    {"OSMutexDel", 0, "OS_MUTEX", (struct_t)OS_MUTEX},
    {"OSMutexPend", 0, "OS_MUTEX", (struct_t)OS_MUTEX},
    {"OSMutexPendAbort", 0, "OS_MUTEX", (struct_t)OS_MUTEX},
    {"OSMutexPost", 0, "OS_MUTEX", (struct_t)OS_MUTEX},
    {"OSTaskChangePrio", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTaskCreate", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTaskDel", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTaskRegGet", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTaskRegSet", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTaskResume", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTaskSuspend", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTaskStkChk", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTaskTimeQuantaSet", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTaskCreateHook", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTaskDelHook", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTaskReturnHook", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTaskSemPendAbort", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTaskSemPost", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTaskSemSet", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTaskQFlush", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTaskQPendAbort", 0, "OS_TCB", (struct_t)OS_TCB},
    {"OSTaskQPost", 0, "OS_TCB", (struct_t)OS_TCB},
};

#endif

#endif