// AUTOGENERATED FILE

struct call_attrs_t {
	uint64_t disabled;
	uint64_t timeout;
	uint64_t prog_timeout;
	uint64_t ignore_return;
	uint64_t breaks_returns;
};

struct call_props_t {
	int fail_nth;
};

#define read_call_props_t(var, reader)          \
	{                                       \
		(var).fail_nth = (int)(reader); \
	}

#if GOOS_ucos
#define GOOS "ucos"

#if GOARCH_arm
#define GOARCH "arm"
#define SYZ_REVISION "45dbc15f20d1c5e7835af260fb52cdd3bb48d04c"
#define SYZ_EXECUTOR_USES_FORK_SERVER 0
#define SYZ_EXECUTOR_USES_SHMEM 0
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
#endif

#endif
